<?php

use yii\db\Migration;
use mhndev\yii2Media\Models\Media;

/**
 * Handles the creation for table `media`.
 */
class m160920_112139_create_media_table extends Migration
{
    public $tableName;

    /**
     * 
     */
    public function init()
    {
        $this->tableName    =   Media::tableName();
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function up()
    {
        $this->createTable($this->tableName, [
            'id' => $this->primaryKey(),
            'owner' => $this->string(),
            'owner_id' => $this->string(),
            'entity' => $this->string(),
            'entity_id' => $this->string(),
            'mime_type' => $this->string(),
            'file_type' => $this->string(),
            'size' => $this->float(),
            'default' => $this->boolean()->defaultValue(0),
            'path' => $this->string(),
            'link' => $this->string(),
            'type'=> $this->string(),
            'created_at'=> $this->dateTime(),
            'updated_at'=> $this->dateTime()
        ]);

        $this->createIndex('entity_find_by_entity_index', $this->tableName, ['entity', 'entity_id', 'mime_type', 'type']);
        $this->createIndex('entity_find_by_path_index', $this->tableName, ['path']);
        $this->createIndex('entity_find_by_link_index', $this->tableName, ['link']);
        $this->createIndex('entity_find_by_owner_index', $this->tableName, ['owner', 'owner_id']);
    }

    /**
     * @inheritdoc
     */
    public function down()
    {
        $this->dropTable($this->tableName);
    }
}
