<?php

use yii\db\Migration;
use mhndev\yii2Media\Models\Media;


class m161002_144225_add_status_field_to_media extends Migration
{
    public $tableName;

    /**
     *
     */
    public function init()
    {
        $this->tableName    =   Media::tableName();
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function up()
    {
        $this->addColumn($this->tableName, 'status', 'ENUM("DRAFTED", "ACCEPTED", "REJECTED", "DELETED") DEFAULT "DRAFTED"');
    }

    public function down()
    {
        $this->dropColumn($this->tableName, 'status');
    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
